#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "$0")")/../.." || exit 0
[ "$(git branch --show-current)" = main ] || exit 0
(git fetch --quiet origin main && git merge --quiet --ff-only origin/main) </dev/null >/dev/null 2>&1 &
exit 0
